// Jpnhg3PymtEnq.idl : IDL source for Jpnhg3PymtEnq.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Jpnhg3PymtEnq.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	//4A115E47-B717-461C-BF08-1C82295523DC - ASAL
	//4072112A-5146-4568-9277-A8B95629EDC9 - NEW 

	[
		object,
		uuid(4072112A-5146-4568-9277-A8B95629EDC9),
		dual,
		helpstring("IJpnhg3PymtEnqService_L1 Interface"),
		pointer_default(unique)
	]
	interface IJpnhg3PymtEnqService_L1 : IDispatch
	{
		[helpstring("method Execute")] HRESULT Execute([in]SAFEARRAY (unsigned char) pDataReq, [out/*,retval*/]SAFEARRAY (unsigned char) *pDataResp);
	};

[
	//CA78620E-4294-4CA6-B6D3-1935D90AF5FB - ASAL
	//AB53332E-DBDF-46F3-BEEB-40F41DF096CD - NEW
	uuid(AB53332E-DBDF-46F3-BEEB-40F41DF096CD),
	version(1.0),
	helpstring("Jpnhg3PymtEnq 1.0 Type Library")
]
library JPNHG3PYMTENQLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		//749E1A93-8DE2-412A-8AD6-72B7FFA32F2C - asal
		//F4467448-9F31-499E-8B8A-D0D4FEE28B82 - new
		uuid(F4467448-9F31-499E-8B8A-D0D4FEE28B82),
		helpstring("Jpnhg3PymtEnqService_L1 Class")
	]
	coclass Jpnhg3PymtEnqService_L1
	{
		[default] interface IJpnhg3PymtEnqService_L1;
	};
};
